#!/bin/bash

CONTEST=$1
CF_URL="https://codeforces.com/contest"
INSTALL_DIR=$HOME/.local/share/cf-cli
TEMP_FILE=$(mktemp)


status_code=$(curl --head --write-out %{http_code} --silent --output /dev/null "$CF_URL/$CONTEST")
[ $status_code -ne 200 ] && exit
 
for i in a b c d e f g
do
    status_code=$(curl --write-out %{http_code} --silent --output $TEMP_FILE "$CF_URL/$CONTEST/problem/$i")

    if [[ status_code -eq 200 ]]
    then
        mkdir "$i"
        cd "$i"

        cat $TEMP_FILE | pup 'div.input pre text{}' | sed '$ d' > input1 
        cat $TEMP_FILE | pup 'div.output pre text{}' | sed '$ d' > output1 

        cp "$INSTALL_DIR/Template.java" ./Solution.java
        cp "$INSTALL_DIR/test" ./

        cd ..
    fi
done


rm $TEMP_FILE
